### PR TITLE
Add unicode support.

### PR DESCRIPTION
**Pull request by cdepillabout**
This is the same pull request from the following link, factored out into a separate module.

https://github.com/purescript/purescript-strings/pull/57

In commit f8470e5898954680, I update the documentation to be PureScript style instead of Haskell style.

There are a couple TODOs left in the code, but they can all be completed after this is merged in and released.

### CODE REVIEW

**Comment by cdepillabout** [comment]
@garyb / @paf31, would you be able to do a quick\* review of this?
- This pull request is quite big, so focusing on the `Data.Char.Unicode` module might be a better time investment.

**Comment by paf31** [comment]
I'll have a look over this this week, thanks! You should run your generator script though, no? And perhaps a test file would be useful as additional documentation, with the output of `pulp docs`.

As maintainer of a contrib project, you obviously have final say over what goes into the releases.

**Comment by cdepillabout** [comment]
@paf31 Thanks!  It's really helpful.

The generated output is in `src/Data/Char/Unicode/Internal.purs`.  It should be part of this PR.

I'll work on getting some tests together this week.

**Comment by cdepillabout** [comment]
@paf31 / @garyb:

Could you enable travis for this repo?
https://travis-ci.org/profile/purescript-contrib

I'm not an admin, so it looks like I can't do it.

**Comment by cdepillabout** [comment]
Unit tests have been added cc4e892.  Documentation has been added in d0277cf.

This should be ready for release.

**Comment by garyb** [comment]
Travis is enabled now. You might have to push again or something to get it to build the PR though, I think?

**Comment by cdepillabout** [comment]
I've added the `digitToInt` function in commit ed8e045.

**Comment by cdepillabout** [comment]
Looks like tests are passing too.

**Comment by garyb** [comment]
Yep, looking good!

**Comment by cdepillabout** [comment]
If there are no objections, I'll release this in about 24 hours.

**Comment by paf31** [comment]
Looks good to me :+1:

**Comment by cdepillabout** [comment]
Alright, I've released to bower and [pursuit](https://pursuit.purescript.org/packages/purescript-unicode/0.0.1).

@paf31 and @garyb, Thanks!

**Pull request merged**
