### PR TITLE
Updates for 0.11

### PR DESCRIPTION
**Pull request by paf31**
The test dependencies still need updating, but we will need to wait for `purescript-spec` to be updated. Perhaps it's better to release this now, and then update `purescript-parsing`.

### CODE REVIEW

**Comment by cdepillabout** [comment]
This looks good to me.  Thanks!

**Comment by cdepillabout** [comment]
@paf31 purescript-unicode is currently v2.0.2.  It should be bumped to v2.0.3 since the code didn't change at all, right?  No need to bump it to v3.0.0 (like `purescript-maybe`, `purescript-foldable-traversable`, etc), right?

**Comment by paf31** [comment]
It needs a major version bump since it involves major version bumps in dependencies.

**Comment by cdepillabout** [comment]
Okay, that makes sense.  I'll bump it to v3.0.0.  Thanks!

**Pull request merged**
