### PR TITLE
Implement bsearch

### PR DESCRIPTION
**Pull request by natefaubion**
This implements a working binary search. It also removes calls to foldable functions that are always worst-case. This is a _significant_ performance improvement, obviously.

### CODE REVIEW

**Comment by cdepillabout** [comment]
@natefaubion Thanks!

The changes look good to me.  This should fix some of the problems with #12.

Unfortunately, I will not have an environment to be able to test these changes and make a release for another week or two.  I was looking for the Settings tab to be able to add you as a owner (or maintainer?) for this repository.  That way you'd be able to make a release on your own if you need these changes in a timely fashion.  However it doesn't look like I have permissions to add/remove maintainers.  If you would like an updated version of purescript-unicode within the next few days, you'll have to message paf31 or garyb to add you as a maintainer.

By the way, the `src/Data/Char/Unicode/Internal.purs` file is actually automatically generated by the [`ubconfc`](https://github.com/purescript-contrib/purescript-unicode/blob/master/ubconfc) script.  If you do get added as a maintainer and want to do the release, you should add your changes to this file as well (and possibly even regenerate the `src/Data/Char/Unicode/Internal.purs` file).  I discuss this unfortunate state of events a little in #13.

**Comment by paulyoung** [comment]
@garyb do you think you could help with adding @natefaubion as a maintainer, or otherwise help get this release sooner?

**Comment by natefaubion** [comment]
@cdepillabout Thanks for letting me know! I've updated the script.

**Comment by garyb** [comment]
@natefaubion is now in the team that has write access :)

**Pull request merged**
