### PR TITLE
Update according to Contributors library guidelines

### PR DESCRIPTION
**Pull request by thomashoneyman**
This pull request is part of an effort to update and standardize the Contributors libraries according to the [Library Guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md). Specifically, it:

1. Adjusts the files and repository structure according to the [repository structure](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#repository-structure) section of the guidelines, which includes standard pr templates, issue templates, CI in GitHub Actions, ensures the project uses Spago, and so on.
2. Updates the README and documentation according to the [documentation](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md#documentation) section of the guidelines. This is a first step towards ensuring Contributors libraries have adequate module documentation, READMEs, a docs directory, and tests (even if just usage examples) in a `test` directory.
3. Updates labels where relevant to help folks better sift through issues on this library and get started contributing.

This PR is the groundwork for followup efforts to ensure contributor libraries are kept up-to-date, documented, tested, and accessible to users and new contributors.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
This build is failing because several of the tests fail due to an "illegal space character." These characters were disallowed in version 0.13.x of the PureScript compiler.

@cdepillabout (or anyone else I should ask?), do you have suggestions on how to handle these tests?

**Comment by cdepillabout** [comment]
@thomashoneyman Thanks for sending this PR!

Everything looks good here.

> This build is failing because several of the tests fail due to an "illegal space character." These characters were disallowed in version 0.13.x of the PureScript compiler.

I took a quick look at the tests, but CI appears to be failing on commit 0aaa87b with the following error (https://github.com/purescript-contrib/purescript-unicode/runs/1212618133#step:8:71):

```
[1/1 ErrorParsingModule] test/Test/Data/Char/Unicode.purs:78:27

  78          generalCategory '\31' `shouldEqual` Just Control
                                ^
  Unable to parse module:
  Illegal character escape code
```

It sounds like escaped characters like `'\31'` are no longer legal?  Do you have a suggestion on how to generate ascii character 31 (which, according to `man ascii`, is hex `x1f`, `US  (unit separator)`)?

Otherwise, I'd be completely fine with just disabling the tests for now and adding an issue about re-enabling them when someone has time to figure out a fix.

**Comment by thomashoneyman** [comment]
Sorry, I misspoke — this is the error I was referring to, and no I unfortunately don’t know how to generate that character for the purpose of the tests. I can disable just the affected three or so tests and open an issue to look into re-enabling them.

**Comment by cdepillabout** [comment]
> I can disable just the affected three or so tests and open an issue to look into re-enabling them.

That sounds like the easiest thing to do for now.

Other than that, I think this looks good.

**Pull request merged**
